[tool.poetry]
name = "youtube"
version = "0.1.0"
description = ""
authors = ["Flancian <0@flancia.org>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pytube = "^15.0.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
